[workspace]
members = ["crates/*"]

[workspace.dependencies]
anyhow = "1.0.71"
apecs = "0.7.0"
async-trait = "0.1.68"
byteorder = "1.4.3"
composition-parsing = { path = "./crates/composition-parsing" }
composition-protocol = { path = "./crates/composition-protocol" }
composition-world = { path = "./crates/composition-world" }
serde = { version = "1.0.160", features = ["serde_derive"] }
serde_json = "1.0.96"
thiserror = "1.0.40"
tokio = { version = "1.28.0", features = ["full"] }
tracing = { version = "0.1.37", features = ["log"] }

[package]
name = "composition"
version = "0.1.0"
edition = "2021"
authors = ["Garen Tyler <garentyler@garen.dev>"]
description = "An extremely fast Minecraft server"
license = "MIT"
build = "build.rs"

[features]
default = []
update_1_20 = ["composition-protocol/update_1_20"]

[dependencies]
base64 = "0.21.0"
clap = { version = "4.2.7", features = ["derive"] }
composition-parsing = { workspace = true }
composition-protocol = { workspace = true }
once_cell = "1.17.1"
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-util = "0.7.8"
toml = "0.7.3"
tracing = { workspace = true }
tracing-subscriber = { version = "0.3.17", features = ["tracing-log"] }
tracing-appender = "0.2.2"

# Unused but possibly useful dependencies:
# async-trait = "0.1.48"
# backtrace = "0.3.50"
# colorful = "0.2.1"
# ctrlc = "3.1.8"
# fastnbt = "*"
# futures = "0.3.28"
# mojang-api = "0.6.1"
# ozelot = "0.9.0" # Ozelot 0.9.0 supports protocol version 578 (1.15.2)
# quartz_nbt = { version = "0.2.6", features = ["serde"] }
# radix64 = "0.6.2"
# toml = "0.5.6"
# uuid = "0.8.2"
