[workspace]
members = [ "crates/*", "crates/*/examples/*" ]

[package]
name = "composition"
version = "0.1.0"
edition = "2021"
authors = ["Garen Tyler <garentyler@garen.dev>"]
description = "An extremely fast Minecraft server"
license = "MIT"

[dependencies]
composition-core = { path = "./crates/composition-core" }
log = "0.4"
tokio = "1"
