[package]
name = "composition"
version = "0.1.0"
authors = ["Garen Tyler <garentyler@gmail.com>"]
edition = "2018"

[dependencies]
log = "*"
fern = { version = "0.6", features = ["colored"] }
chrono = "0.4.13"
serde = { version = "1.0.114", features = ["serde_derive"]}
serde_json = "1.0.59"
toml = "0.5"
radix64 = "0.3.0"
tokio = { version = "1", features = ["full"] }
async-trait = "0.1.48"
lazy_static = "1.4.0"
ctrlc = "3.1.8"
# colorful = "0.2.1"
# ozelot = "0.9.0" # Ozelot 0.9.0 supports protocol version 578 (1.15.2)
# toml = "0.5.6"
# base64 = "0.12.3"
# mojang-api = "0.6.1"
# backtrace = "0.3.50"
