# This file is only meant to provide a convenient dev environment.
# For prod images, look at docker-bake.hcl and README.md.
services:
  reference:
    container_name: reference
    restart: unless-stopped
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "1.21.1"
      ONLINE_MODE: "false"
      NETWORK_COMPRESSION_THRESHOLD: "-1"
