name: ci

on:
  push:
    branches: ["main"]

jobs:
  clippy:
    name: Run clippy analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run clippy
        run: cargo clippy --all-targets --all-features
  bake:
    name: Build and push Docker images
    runs-on: ubuntu-latest
    needs: clippy
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Login to git.garen.dev Container Registry
        uses: docker/login-action@v3
        with:
          registry: git.garen.dev
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64, linux/arm64
      - name: Bake and push
        uses: docker/bake-action@v6
        with:
          files: docker-bake.hcl
          source: .
          push: true
