name: ci

on:
  push:

jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 -
      - name: Build and push images in bake file
        uses: docker/bake-action@v6
        with:
          push: false

