[package]
name = "composition-protocol"
version = "0.1.0"
edition = "2021"
authors = ["Garen Tyler <garentyler@garen.dev>"]
description = "The Minecraft protocol implemented in a network-agnostic way"
license = "MIT"

[dependencies]
anyhow = "1.0.71"
byteorder = "1.4.3"
serde_json = "1.0.96"
thiserror = "1.0.40"
tracing = { workspace = true }
