[package]
name = "composition-protocol"
version = "0.1.0"
edition = "2021"
authors = ["Garen Tyler <garentyler@garen.dev>"]
description = "The Minecraft protocol implemented in a network-agnostic way"
license = "MIT"

[dependencies]
anyhow = { workspace = true }
byteorder = { workspace = true }
composition-parsing = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[features]
default = []
update_1_20 = []
