[package]
name = "composition-protocol"
version = "0.1.0"
edition = "2021"
authors = ["Garen Tyler <garentyler@garen.dev>"]
description = "The Minecraft protocol implemented in a network-agnostic way"
license = "MIT"

[dependencies]
anyhow = "1.0.69"
tracing = { workspace = true }
byteorder = "1"
serde_json = "1.0.94"
thiserror = "1.0.39"
