[package]
name = "composition-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7"
serde_json = "1.0.94"
anyhow = "1.0.69"
thiserror = "1.0.39"

[[example]]
name = "packet_logger"
path = "examples/packet_logger/src/main.rs"
